// Generated by Selenium IDE
package es.uma.informatica.sii.Secretaria.tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AsignarSuiteIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void asignarSuiteIT() {
    driver.get("http://localhost:8080/Secretaria-WAR/faces/readdeleteMatricula.xhtml");
    driver.manage().window().setSize(new Dimension(735, 573));
    driver.findElement(By.id("j_idt6:cursoAcademico")).click();
    driver.findElement(By.id("j_idt6:cursoAcademico")).sendKeys("2020/2021");
    driver.findElement(By.id("j_idt6:expediente")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("102474113");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(3)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//input[@value=\'Volver\']")).click();
    driver.findElement(By.cssSelector(".botonS")).click();
    driver.findElement(By.cssSelector("th:nth-child(1) > .boton")).click();
    driver.findElement(By.xpath("//form[@id=\'j_idt7\']/table/tbody/tr/td[8]/input")).click();
    driver.findElement(By.cssSelector(".botonS")).click();
    driver.findElement(By.cssSelector("th:nth-child(5) > .boton")).click();
    driver.findElement(By.cssSelector("input:nth-child(20)")).click();
    driver.findElement(By.id("j_idt6:cursoAcademico")).click();
    driver.findElement(By.id("j_idt6:cursoAcademico")).sendKeys("2020/2021");
    driver.findElement(By.id("j_idt6:expediente")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("102474113");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(3)")).click();
    assertEquals(driver.findElement(By.id("j_idt6:j_idt38:0:grupo")).getText(), "Grupo [id=1231540, curso=1, letra=B]");
    driver.findElement(By.id("j_idt6:expediente")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("102474119");
    driver.findElement(By.name("j_idt6:j_idt15")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(1) > td:nth-child(3)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//input[@value=\'Volver\']")).click();
    driver.findElement(By.cssSelector(".botonS")).click();
    driver.findElement(By.cssSelector("th:nth-child(1) > .boton")).click();
    driver.findElement(By.xpath("//form[@id=\'j_idt7\']/table/tbody/tr/td[9]/input")).click();
    {
      WebElement dropdown = driver.findElement(By.id("form:tablaAsignarManual:0:letraSeleccionada"));
      dropdown.findElement(By.xpath("//option[. = 'A']")).click();
    }
    /*{
      WebElement element = driver.findElement(By.id("form:tablaAsignarManual:0:letraSeleccionada"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("form:tablaAsignarManual:0:letraSeleccionada"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("form:tablaAsignarManual:0:letraSeleccionada"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }*/
    driver.findElement(By.id("form:tablaAsignarManual:0:letraSeleccionada")).click();
    
    {
      WebElement dropdown = driver.findElement(By.id("form:tablaAsignarManual:1:letraSeleccionada"));
      dropdown.findElement(By.xpath("//option[. = 'A']")).click();
    }
    /*{
      WebElement element = driver.findElement(By.id("form:tablaAsignarManual:1:letraSeleccionada"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("form:tablaAsignarManual:1:letraSeleccionada"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("form:tablaAsignarManual:1:letraSeleccionada"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }*/
    driver.findElement(By.id("form:tablaAsignarManual:1:letraSeleccionada")).click();
    driver.findElement(By.xpath("//form[@id=\'form\']/input[3]")).click();
    driver.findElement(By.cssSelector(".botonS")).click();
    driver.findElement(By.cssSelector(".botonS")).click();
    driver.findElement(By.cssSelector("th:nth-child(5) > .boton")).click();
    driver.findElement(By.cssSelector("input:nth-child(20)")).click();
    driver.findElement(By.id("j_idt6:cursoAcademico")).click();
    driver.findElement(By.id("j_idt6:cursoAcademico")).sendKeys("2020/2021");
    driver.findElement(By.id("j_idt6:expediente")).click();
    driver.findElement(By.id("j_idt6:expediente")).sendKeys("102474119");
    driver.findElement(By.xpath("//form[@id=\'j_idt6\']/input[3]")).click();
    driver.findElement(By.id("j_idt6:j_idt38:0:grupo")).click();
    assertEquals(driver.findElement(By.id("j_idt6:j_idt38:0:grupo")).getText(), "Grupo [id=1231546, curso=1, letra=A]");
  }
}
