package es.uma.informatica.sii.Secretaria.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CRUDAlumnoSuiteIT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void createAlumnoIT() {
		driver.get("http://localhost:8080/Secretaria-WAR/faces/gestionarEntidades.xhtml");
		driver.manage().window().setSize(new Dimension(810, 861));
		driver.findElement(By.cssSelector("input:nth-child(7)")).click();
		driver.findElement(By.id("j_idt6:id")).click();
		driver.findElement(By.id("j_idt6:id")).sendKeys("8");
		driver.findElement(By.id("j_idt6:dni")).click();
		driver.findElement(By.id("j_idt6:dni")).sendKeys("25630763T");
		driver.findElement(By.id("j_idt6:nombre")).click();
		driver.findElement(By.id("j_idt6:nombre")).sendKeys("Julio");
		driver.findElement(By.id("j_idt6:apellido1")).click();
		driver.findElement(By.id("j_idt6:apellido1")).sendKeys("Perez");
		driver.findElement(By.id("j_idt6:apellido2")).click();
		driver.findElement(By.id("j_idt6:apellido2")).sendKeys("Gonzalez");
		driver.findElement(By.id("j_idt6:emailInstitucional")).click();
		driver.findElement(By.id("j_idt6:emailInstitucional")).sendKeys("julio@uma.es");
		driver.findElement(By.id("j_idt6:emailPersonal")).click();
		driver.findElement(By.id("j_idt6:emailPersonal")).sendKeys("julio@gmail.com");
		driver.findElement(By.id("j_idt6:numeroArchivo")).click();
		driver.findElement(By.id("j_idt6:numeroArchivo")).sendKeys("4785698569");
		driver.findElement(By.id("j_idt6:numeroMovil")).click();
		driver.findElement(By.id("j_idt6:numeroMovil")).sendKeys("62547814");
		driver.findElement(By.id("j_idt6:numeroTelefono")).click();
		driver.findElement(By.id("j_idt6:numeroTelefono")).sendKeys("95784123");
		driver.findElement(By.id("j_idt6:direccion")).click();
		driver.findElement(By.id("j_idt6:direccion")).sendKeys("Calle Larga");
		driver.findElement(By.id("j_idt6:localidad")).click();
		driver.findElement(By.id("j_idt6:localidad")).sendKeys("Malaga");
		driver.findElement(By.id("j_idt6:provincia")).click();
		driver.findElement(By.id("j_idt6:provincia")).sendKeys("Malaga");
		driver.findElement(By.id("j_idt6:cp")).click();
		driver.findElement(By.id("j_idt6:cp")).sendKeys("29010");
		driver.findElement(By.name("j_idt6:j_idt38")).click();
		driver.findElement(By.cssSelector("ul")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector("li"));
			assert (elements.size() > 0);
		}
		driver.findElement(By.cssSelector("input:nth-child(4)")).click();
		driver.findElement(By.cssSelector("input:nth-child(8)")).click();
		driver.findElement(By.id("j_idt6:id")).click();
		driver.findElement(By.id("j_idt6:id")).sendKeys("8");
		driver.findElement(By.name("j_idt6:j_idt12")).click();
		driver.findElement(By.cssSelector("li")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector("li"));
			assert (elements.size() > 0);
		}
	}

	@Test
	public void updateAlumnoIT() {
		driver.get("http://localhost:8080/Secretaria-WAR/faces/gestionarEntidades.xhtml");
		driver.manage().window().setSize(new Dimension(785, 841));
		driver.findElement(By.cssSelector("input:nth-child(7)")).click();
		driver.findElement(By.id("j_idt6:id")).click();
		driver.findElement(By.id("j_idt6:id")).sendKeys("1");
		driver.findElement(By.id("j_idt6:dni")).click();
		driver.findElement(By.id("j_idt6:dni")).sendKeys("254789E");
		driver.findElement(By.id("j_idt6:nombre")).click();
		driver.findElement(By.id("j_idt6:nombre")).sendKeys("PepitoCambiado");
		driver.findElement(By.id("j_idt6:apellido1")).click();
		driver.findElement(By.id("j_idt6:apellido1")).sendKeys("PalotesNuevo");
		driver.findElement(By.id("j_idt6:apellido2")).click();
		driver.findElement(By.id("j_idt6:apellido2")).sendKeys("PerezNuevo");
		driver.findElement(By.id("j_idt6:emailInstitucional")).click();
		driver.findElement(By.id("j_idt6:emailInstitucional")).sendKeys("julio@uma.es");
		driver.findElement(By.id("j_idt6:emailPersonal")).click();
		driver.findElement(By.id("j_idt6:emailPersonal")).sendKeys("julio@gmail.com");
		driver.findElement(By.id("j_idt6:numeroArchivo")).click();
		driver.findElement(By.id("j_idt6:numeroArchivo")).sendKeys("4785698569");
		driver.findElement(By.id("j_idt6:numeroMovil")).click();
		driver.findElement(By.id("j_idt6:numeroMovil")).sendKeys("62547814");
		driver.findElement(By.id("j_idt6:numeroTelefono")).click();
		driver.findElement(By.id("j_idt6:numeroTelefono")).sendKeys("95784123");
		driver.findElement(By.id("j_idt6:direccion")).click();
		driver.findElement(By.id("j_idt6:direccion")).sendKeys("Calle Larga");
		driver.findElement(By.id("j_idt6:localidad")).click();
		driver.findElement(By.id("j_idt6:localidad")).sendKeys("Malaga");
		driver.findElement(By.id("j_idt6:provincia")).click();
		driver.findElement(By.id("j_idt6:provincia")).sendKeys("Malaga");
		driver.findElement(By.id("j_idt6:cp")).click();
		driver.findElement(By.id("j_idt6:cp")).sendKeys("29010");
		driver.findElement(By.name("j_idt6:j_idt39")).click();
		driver.findElement(By.cssSelector("li")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector("li"));
			assert (elements.size() > 0);
		}
		driver.findElement(By.cssSelector("input:nth-child(4)")).click();
		driver.findElement(By.cssSelector("input:nth-child(8)")).click();
		driver.findElement(By.id("j_idt6:id")).click();
		driver.findElement(By.id("j_idt6:id")).sendKeys("1");
		driver.findElement(By.name("j_idt6:j_idt12")).click();
		driver.findElement(By.cssSelector("li")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector("li"));
			assert (elements.size() > 0);
		}

	}
	
	@Test
	public void deleteAlumnoIT() {
		driver.get("http://localhost:8080/Secretaria-WAR/faces/gestionarEntidades.xhtml");
		driver.manage().window().setSize(new Dimension(785, 841));
		driver.findElement(By.cssSelector("input:nth-child(8)")).click();
		driver.findElement(By.id("j_idt6:id")).click();
		driver.findElement(By.id("j_idt6:id")).sendKeys("8");
		driver.findElement(By.name("j_idt6:j_idt11")).click();
		driver.findElement(By.cssSelector("ul")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector("li"));
			assert (elements.size() > 0);
		}
		driver.findElement(By.name("j_idt6:j_idt12")).click();
		driver.findElement(By.cssSelector("li")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector("li"));
			assert (elements.size() > 0);
		}
		{
			List<WebElement> elements = driver.findElements(By.id("j_idt6"));
			assert (elements.size() > 0);
		}
	}

}
