// Generated by Selenium IDE
package es.uma.informatica.sii.Secretaria.tests;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class EncuestaSuiteIT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Requisitos({"RF14"})
	@Test
	public void enviarCorrecta() {
		driver.get("http://localhost:8080/Secretaria-WAR/faces/correo.xhtml");
		driver.manage().window().setSize(new Dimension(735, 573));
		driver.findElement(By.id("j_idt7:correo")).click();
		driver.findElement(By.cssSelector(".caja")).click();
		driver.findElement(By.id("j_idt7:correo")).sendKeys("pabloespinosa122@gmail.com");
		{
			String value = driver.findElement(By.id("j_idt7:correo")).getAttribute("value");
			assertTrue(value.matches("^[\\w-+]+(\\.[\\w-]{1,62}){0,126}@gmail.com"));
		}
		driver.findElement(By.name("j_idt7:j_idt9")).click();
	}

	@Requisitos({"RF14"})
	@Test
	public void enviarFalsa() {
		driver.get("http://localhost:8080/Secretaria-WAR/faces/correo.xhtml");
		driver.manage().window().setSize(new Dimension(735, 573));
		driver.findElement(By.id("j_idt7:correo")).click();
		driver.findElement(By.cssSelector(".caja")).click();
		driver.findElement(By.id("j_idt7:correo")).sendKeys("esto no es un correo");
		{
			String value = driver.findElement(By.id("j_idt7:correo")).getAttribute("value");
			assertFalse(value.matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)@gmail.com"));
		}
		driver.findElement(By.name("j_idt7:j_idt9")).click();
	}

	@Requisitos({ "RF14" })
	@Test
	public void rellenarEncuesta() {
		driver.get("http://localhost:8080/Secretaria-WAR/faces/rellenarEncuesta.xhtml");
		driver.manage().window().setSize(new Dimension(735, 573));
		driver.findElement(By.id("form:Dni")).click();
		driver.findElement(By.id("form:Dni")).sendKeys("254789A");
		driver.findElement(By.name("form:j_idt9")).click();
		driver.findElement(By.cssSelector("ul")).click();
		assertEquals(driver.findElement(By.cssSelector("li")).getText(), "Alumno encontrado");
		{
			WebElement dropdown = driver.findElement(By.name("form:tablaEncuesta:0:j_idt17"));
			dropdown.findElement(By.xpath("//option[. = 'A']")).click();
		}
		driver.findElement(By.name("form:tablaEncuesta:0:j_idt17")).click();
		{
			WebElement dropdown = driver.findElement(By.name("form:tablaEncuesta:1:j_idt17"));
			dropdown.findElement(By.xpath("//option[. = 'A']")).click();
		}
		driver.findElement(By.name("form:tablaEncuesta:1:j_idt17")).click();
		driver.findElement(By.name("form:j_idt19")).click();
		driver.close();
	}
}
