package es.uma.informatica.sii.Secretaria.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class GestionGrupoSuiteIT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void cambioDeGrupoIT() {
		driver.get("http://localhost:8080/Secretaria-WAR/faces/gestionarCambio.xhtml");
		driver.manage().window().setSize(new Dimension(735, 573));
		driver.findElement(By.id("GestionForm:DNIAlumno")).click();
		driver.findElement(By.id("GestionForm:DNIAlumno")).sendKeys("254789E");
		driver.findElement(By.id("GestionForm:botonBuscar")).click();
		driver.findElement(By.cssSelector("table")).click();
		
		assertEquals(driver.findElement(By.id("j_idt12:0:DNI")).getText(), "254789E");
		
		driver.get("http://localhost:8080/Secretaria-WAR/faces/escogerGrupo2.xhtml");
		driver.manage().window().setSize(new Dimension(735, 573));
		driver.findElement(By.xpath("//a/span")).click();
		{
			WebElement dropdown = driver.findElement(By.id("form:listaFilas:0:letraSeleccion"));
			dropdown.findElement(By.xpath("//option[. = 'B']")).click();
		}
		{
			WebElement element = driver.findElement(By.id("form:listaFilas:0:letraSeleccion"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.id("form:listaFilas:0:letraSeleccion"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.id("form:listaFilas:0:letraSeleccion"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.id("form:listaFilas:0:letraSeleccion")).click();
		driver.findElement(By.xpath("//div[@id=\'form:listaFilas:0:filaEdicion\']/a[2]/span")).click();
		driver.findElement(By.id("form:confirmar")).click();
		driver.findElement(By.xpath("//td[2]")).click();
		
		assertEquals(driver.findElement(By.id("form:listaFilas:0:filaSelec")).getText(), "B");
	}

}
